/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* BtnIsr */
#define BtnIsr__INTC_CORTEXM4_ASSIGNED 1
#define BtnIsr__INTC_CORTEXM4_PRIORITY 7u
#define BtnIsr__INTC_NUMBER 122u
#define BtnIsr_INTC_CORTEXM4_ASSIGNED 1
#define BtnIsr_INTC_CORTEXM4_PRIORITY 7u
#define BtnIsr_INTC_NUMBER 122u

/* SysInt_1 */
#define SysInt_1__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_1__INTC_CORTEXM4_PRIORITY 7u
#define SysInt_1__INTC_NUMBER 123u
#define SysInt_1_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_1_INTC_CORTEXM4_PRIORITY 7u
#define SysInt_1_INTC_NUMBER 123u

/* SysInt_2 */
#define SysInt_2__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_2__INTC_CORTEXM4_PRIORITY 5u
#define SysInt_2__INTC_NUMBER 124u
#define SysInt_2_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_2_INTC_CORTEXM4_PRIORITY 5u
#define SysInt_2_INTC_NUMBER 124u

/* SysInt_3 */
#define SysInt_3__INTC_CORTEXM4_ASSIGNED 1
#define SysInt_3__INTC_CORTEXM4_PRIORITY 7u
#define SysInt_3__INTC_NUMBER 92u
#define SysInt_3_INTC_CORTEXM4_ASSIGNED 1
#define SysInt_3_INTC_CORTEXM4_PRIORITY 7u
#define SysInt_3_INTC_NUMBER 92u

/* ADC_1_IRQ */
#define ADC_1_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define ADC_1_IRQ__INTC_CORTEXM4_PRIORITY 2u
#define ADC_1_IRQ__INTC_NUMBER 138u
#define ADC_1_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define ADC_1_IRQ_INTC_CORTEXM4_PRIORITY 2u
#define ADC_1_IRQ_INTC_NUMBER 138u

/* time_out_int */
#define time_out_int__INTC_CORTEXM4_ASSIGNED 1
#define time_out_int__INTC_CORTEXM4_PRIORITY 2u
#define time_out_int__INTC_NUMBER 94u
#define time_out_int_INTC_CORTEXM4_ASSIGNED 1
#define time_out_int_INTC_CORTEXM4_PRIORITY 2u
#define time_out_int_INTC_NUMBER 94u

/* encoder_L_int */
#define encoder_L_int__INTC_CORTEXM4_ASSIGNED 1
#define encoder_L_int__INTC_CORTEXM4_PRIORITY 3u
#define encoder_L_int__INTC_NUMBER 125u
#define encoder_L_int_INTC_CORTEXM4_ASSIGNED 1
#define encoder_L_int_INTC_CORTEXM4_PRIORITY 3u
#define encoder_L_int_INTC_NUMBER 125u

/* encoder_R_int */
#define encoder_R_int__INTC_CORTEXM4_ASSIGNED 1
#define encoder_R_int__INTC_CORTEXM4_PRIORITY 3u
#define encoder_R_int__INTC_NUMBER 126u
#define encoder_R_int_INTC_CORTEXM4_ASSIGNED 1
#define encoder_R_int_INTC_CORTEXM4_PRIORITY 3u
#define encoder_R_int_INTC_NUMBER 126u

/* UART_1_SCB_IRQ */
#define UART_1_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define UART_1_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define UART_1_SCB_IRQ__INTC_NUMBER 46u
#define UART_1_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define UART_1_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define UART_1_SCB_IRQ_INTC_NUMBER 46u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
