/*******************************************************************************
* File Name: cyfitter_sysint_cfg.c
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_sysint.h"
#include "cyfitter_sysint_cfg.h"

/* ARM CM4 */
#if (((__CORTEX_M == 4) && (CY_CORE_ID == 0)))

    /* UART_1_SCB_IRQ */
    const cy_stc_sysint_t UART_1_SCB_IRQ_cfg = {
        .intrSrc = (IRQn_Type)UART_1_SCB_IRQ__INTC_NUMBER,
        .intrPriority = UART_1_SCB_IRQ__INTC_CORTEXM4_PRIORITY
    };

    /* SysInt_3 */
    const cy_stc_sysint_t SysInt_3_cfg = {
        .intrSrc = (IRQn_Type)SysInt_3__INTC_NUMBER,
        .intrPriority = SysInt_3__INTC_CORTEXM4_PRIORITY
    };

    /* time_out_int */
    const cy_stc_sysint_t time_out_int_cfg = {
        .intrSrc = (IRQn_Type)time_out_int__INTC_NUMBER,
        .intrPriority = time_out_int__INTC_CORTEXM4_PRIORITY
    };

    /* BtnIsr */
    const cy_stc_sysint_t BtnIsr_cfg = {
        .intrSrc = (IRQn_Type)BtnIsr__INTC_NUMBER,
        .intrPriority = BtnIsr__INTC_CORTEXM4_PRIORITY
    };

    /* SysInt_1 */
    const cy_stc_sysint_t SysInt_1_cfg = {
        .intrSrc = (IRQn_Type)SysInt_1__INTC_NUMBER,
        .intrPriority = SysInt_1__INTC_CORTEXM4_PRIORITY
    };

    /* SysInt_2 */
    const cy_stc_sysint_t SysInt_2_cfg = {
        .intrSrc = (IRQn_Type)SysInt_2__INTC_NUMBER,
        .intrPriority = SysInt_2__INTC_CORTEXM4_PRIORITY
    };

    /* encoder_L_int */
    const cy_stc_sysint_t encoder_L_int_cfg = {
        .intrSrc = (IRQn_Type)encoder_L_int__INTC_NUMBER,
        .intrPriority = encoder_L_int__INTC_CORTEXM4_PRIORITY
    };

    /* encoder_R_int */
    const cy_stc_sysint_t encoder_R_int_cfg = {
        .intrSrc = (IRQn_Type)encoder_R_int__INTC_NUMBER,
        .intrPriority = encoder_R_int__INTC_CORTEXM4_PRIORITY
    };

    /* ADC_1_IRQ */
    const cy_stc_sysint_t ADC_1_IRQ_cfg = {
        .intrSrc = (IRQn_Type)ADC_1_IRQ__INTC_NUMBER,
        .intrPriority = ADC_1_IRQ__INTC_CORTEXM4_PRIORITY
    };

#endif /* ((__CORTEX_M == 4) && (CY_CORE_ID == 0)) */

