/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* echo */
#define echo_0_DRIVEMODE CY_GPIO_DM_PULLUP_DOWN
#define echo_0_INBUF_ENABLED 1u
#define echo_0_INIT_DRIVESTATE 0u
#define echo_0_INIT_MUXSEL 0u
#define echo_0_INPUT_SYNC 2u
#define echo_0_INTERRUPT_MODE CY_GPIO_INTR_RISING
#define echo_0_NUM 5u
#define echo_0_PORT GPIO_PRT9
#define echo_0_SLEWRATE CY_GPIO_SLEW_FAST
#define echo_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define echo_DRIVEMODE CY_GPIO_DM_PULLUP_DOWN
#define echo_INBUF_ENABLED 1u
#define echo_INIT_DRIVESTATE 0u
#define echo_INIT_MUXSEL 0u
#define echo_INPUT_SYNC 2u
#define echo_INTERRUPT_MODE CY_GPIO_INTR_RISING
#define echo_NUM 5u
#define echo_PORT GPIO_PRT9
#define echo_SLEWRATE CY_GPIO_SLEW_FAST
#define echo_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Pin_1 */
#define Pin_1_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define Pin_1_0_INBUF_ENABLED 0u
#define Pin_1_0_INIT_DRIVESTATE 0u
#define Pin_1_0_INIT_MUXSEL 0u
#define Pin_1_0_INPUT_SYNC 2u
#define Pin_1_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_1_0_NUM 1u
#define Pin_1_0_PORT GPIO_PRT10
#define Pin_1_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_1_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_1_DRIVEMODE CY_GPIO_DM_ANALOG
#define Pin_1_INBUF_ENABLED 0u
#define Pin_1_INIT_DRIVESTATE 0u
#define Pin_1_INIT_MUXSEL 0u
#define Pin_1_INPUT_SYNC 2u
#define Pin_1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_1_NUM 1u
#define Pin_1_PORT GPIO_PRT10
#define Pin_1_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UsrBtn */
#define UsrBtn_0_DRIVEMODE CY_GPIO_DM_PULLUP
#define UsrBtn_0_INBUF_ENABLED 1u
#define UsrBtn_0_INIT_DRIVESTATE 1u
#define UsrBtn_0_INIT_MUXSEL 0u
#define UsrBtn_0_INPUT_SYNC 2u
#define UsrBtn_0_INTERRUPT_MODE CY_GPIO_INTR_FALLING
#define UsrBtn_0_NUM 4u
#define UsrBtn_0_PORT GPIO_PRT0
#define UsrBtn_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UsrBtn_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UsrBtn_DRIVEMODE CY_GPIO_DM_PULLUP
#define UsrBtn_INBUF_ENABLED 1u
#define UsrBtn_INIT_DRIVESTATE 1u
#define UsrBtn_INIT_MUXSEL 0u
#define UsrBtn_INPUT_SYNC 2u
#define UsrBtn_INTERRUPT_MODE CY_GPIO_INTR_FALLING
#define UsrBtn_NUM 4u
#define UsrBtn_PORT GPIO_PRT0
#define UsrBtn_SLEWRATE CY_GPIO_SLEW_FAST
#define UsrBtn_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* back_L */
#define back_L_0_DRIVEMODE CY_GPIO_DM_PULLUP_DOWN_IN_OFF
#define back_L_0_INBUF_ENABLED 0u
#define back_L_0_INIT_DRIVESTATE 0u
#define back_L_0_INIT_MUXSEL 0u
#define back_L_0_INPUT_SYNC 2u
#define back_L_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define back_L_0_NUM 1u
#define back_L_0_PORT GPIO_PRT9
#define back_L_0_SLEWRATE CY_GPIO_SLEW_FAST
#define back_L_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define back_L_DRIVEMODE CY_GPIO_DM_PULLUP_DOWN_IN_OFF
#define back_L_INBUF_ENABLED 0u
#define back_L_INIT_DRIVESTATE 0u
#define back_L_INIT_MUXSEL 0u
#define back_L_INPUT_SYNC 2u
#define back_L_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define back_L_NUM 1u
#define back_L_PORT GPIO_PRT9
#define back_L_SLEWRATE CY_GPIO_SLEW_FAST
#define back_L_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* back_R */
#define back_R_0_DRIVEMODE CY_GPIO_DM_PULLUP_DOWN_IN_OFF
#define back_R_0_INBUF_ENABLED 0u
#define back_R_0_INIT_DRIVESTATE 0u
#define back_R_0_INIT_MUXSEL 0u
#define back_R_0_INPUT_SYNC 2u
#define back_R_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define back_R_0_NUM 3u
#define back_R_0_PORT GPIO_PRT9
#define back_R_0_SLEWRATE CY_GPIO_SLEW_FAST
#define back_R_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define back_R_DRIVEMODE CY_GPIO_DM_PULLUP_DOWN_IN_OFF
#define back_R_INBUF_ENABLED 0u
#define back_R_INIT_DRIVESTATE 0u
#define back_R_INIT_MUXSEL 0u
#define back_R_INPUT_SYNC 2u
#define back_R_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define back_R_NUM 3u
#define back_R_PORT GPIO_PRT9
#define back_R_SLEWRATE CY_GPIO_SLEW_FAST
#define back_R_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* RED_LED */
#define RED_LED_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW_IN_OFF
#define RED_LED_0_INBUF_ENABLED 0u
#define RED_LED_0_INIT_DRIVESTATE 0u
#define RED_LED_0_INIT_MUXSEL 0u
#define RED_LED_0_INPUT_SYNC 2u
#define RED_LED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define RED_LED_0_NUM 3u
#define RED_LED_0_PORT GPIO_PRT6
#define RED_LED_0_SLEWRATE CY_GPIO_SLEW_SLOW
#define RED_LED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define RED_LED_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW_IN_OFF
#define RED_LED_INBUF_ENABLED 0u
#define RED_LED_INIT_DRIVESTATE 0u
#define RED_LED_INIT_MUXSEL 0u
#define RED_LED_INPUT_SYNC 2u
#define RED_LED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define RED_LED_NUM 3u
#define RED_LED_PORT GPIO_PRT6
#define RED_LED_SLEWRATE CY_GPIO_SLEW_SLOW
#define RED_LED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* trigger */
#define trigger_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define trigger_0_INBUF_ENABLED 0u
#define trigger_0_INIT_DRIVESTATE 0u
#define trigger_0_INIT_MUXSEL 0u
#define trigger_0_INPUT_SYNC 2u
#define trigger_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define trigger_0_NUM 4u
#define trigger_0_PORT GPIO_PRT9
#define trigger_0_SLEWRATE CY_GPIO_SLEW_FAST
#define trigger_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define trigger_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define trigger_INBUF_ENABLED 0u
#define trigger_INIT_DRIVESTATE 0u
#define trigger_INIT_MUXSEL 0u
#define trigger_INPUT_SYNC 2u
#define trigger_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define trigger_NUM 4u
#define trigger_PORT GPIO_PRT9
#define trigger_SLEWRATE CY_GPIO_SLEW_FAST
#define trigger_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* GREEN_LED */
#define GREEN_LED_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW_IN_OFF
#define GREEN_LED_0_INBUF_ENABLED 0u
#define GREEN_LED_0_INIT_DRIVESTATE 0u
#define GREEN_LED_0_INIT_MUXSEL 0u
#define GREEN_LED_0_INPUT_SYNC 2u
#define GREEN_LED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define GREEN_LED_0_NUM 1u
#define GREEN_LED_0_PORT GPIO_PRT7
#define GREEN_LED_0_SLEWRATE CY_GPIO_SLEW_SLOW
#define GREEN_LED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define GREEN_LED_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW_IN_OFF
#define GREEN_LED_INBUF_ENABLED 0u
#define GREEN_LED_INIT_DRIVESTATE 0u
#define GREEN_LED_INIT_MUXSEL 0u
#define GREEN_LED_INPUT_SYNC 2u
#define GREEN_LED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define GREEN_LED_NUM 1u
#define GREEN_LED_PORT GPIO_PRT7
#define GREEN_LED_SLEWRATE CY_GPIO_SLEW_SLOW
#define GREEN_LED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_1_rx */
#define UART_1_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_1_rx_0_INBUF_ENABLED 1u
#define UART_1_rx_0_INIT_DRIVESTATE 1u
#define UART_1_rx_0_INIT_MUXSEL 18u
#define UART_1_rx_0_INPUT_SYNC 2u
#define UART_1_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_rx_0_NUM 0u
#define UART_1_rx_0_PORT GPIO_PRT5
#define UART_1_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_1_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_1_rx_INBUF_ENABLED 1u
#define UART_1_rx_INIT_DRIVESTATE 1u
#define UART_1_rx_INIT_MUXSEL 18u
#define UART_1_rx_INPUT_SYNC 2u
#define UART_1_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_rx_NUM 0u
#define UART_1_rx_PORT GPIO_PRT5
#define UART_1_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_1_tx */
#define UART_1_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_1_tx_0_INBUF_ENABLED 0u
#define UART_1_tx_0_INIT_DRIVESTATE 1u
#define UART_1_tx_0_INIT_MUXSEL 18u
#define UART_1_tx_0_INPUT_SYNC 2u
#define UART_1_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_tx_0_NUM 1u
#define UART_1_tx_0_PORT GPIO_PRT5
#define UART_1_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_1_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_1_tx_INBUF_ENABLED 0u
#define UART_1_tx_INIT_DRIVESTATE 1u
#define UART_1_tx_INIT_MUXSEL 18u
#define UART_1_tx_INPUT_SYNC 2u
#define UART_1_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_1_tx_NUM 1u
#define UART_1_tx_PORT GPIO_PRT5
#define UART_1_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_1_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* encoder_L */
#define encoder_L_0_DRIVEMODE CY_GPIO_DM_PULLUP
#define encoder_L_0_INBUF_ENABLED 1u
#define encoder_L_0_INIT_DRIVESTATE 1u
#define encoder_L_0_INIT_MUXSEL 0u
#define encoder_L_0_INPUT_SYNC 2u
#define encoder_L_0_INTERRUPT_MODE CY_GPIO_INTR_RISING
#define encoder_L_0_NUM 2u
#define encoder_L_0_PORT GPIO_PRT5
#define encoder_L_0_SLEWRATE CY_GPIO_SLEW_FAST
#define encoder_L_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define encoder_L_DRIVEMODE CY_GPIO_DM_PULLUP
#define encoder_L_INBUF_ENABLED 1u
#define encoder_L_INIT_DRIVESTATE 1u
#define encoder_L_INIT_MUXSEL 0u
#define encoder_L_INPUT_SYNC 2u
#define encoder_L_INTERRUPT_MODE CY_GPIO_INTR_RISING
#define encoder_L_NUM 2u
#define encoder_L_PORT GPIO_PRT5
#define encoder_L_SLEWRATE CY_GPIO_SLEW_FAST
#define encoder_L_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* encoder_R */
#define encoder_R_0_DRIVEMODE CY_GPIO_DM_PULLUP
#define encoder_R_0_INBUF_ENABLED 1u
#define encoder_R_0_INIT_DRIVESTATE 1u
#define encoder_R_0_INIT_MUXSEL 0u
#define encoder_R_0_INPUT_SYNC 2u
#define encoder_R_0_INTERRUPT_MODE CY_GPIO_INTR_RISING
#define encoder_R_0_NUM 3u
#define encoder_R_0_PORT GPIO_PRT5
#define encoder_R_0_SLEWRATE CY_GPIO_SLEW_FAST
#define encoder_R_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define encoder_R_DRIVEMODE CY_GPIO_DM_PULLUP
#define encoder_R_INBUF_ENABLED 1u
#define encoder_R_INIT_DRIVESTATE 1u
#define encoder_R_INIT_MUXSEL 0u
#define encoder_R_INPUT_SYNC 2u
#define encoder_R_INTERRUPT_MODE CY_GPIO_INTR_RISING
#define encoder_R_NUM 3u
#define encoder_R_PORT GPIO_PRT5
#define encoder_R_SLEWRATE CY_GPIO_SLEW_FAST
#define encoder_R_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* forward_L */
#define forward_L_0_DRIVEMODE CY_GPIO_DM_PULLUP_DOWN_IN_OFF
#define forward_L_0_INBUF_ENABLED 0u
#define forward_L_0_INIT_DRIVESTATE 1u
#define forward_L_0_INIT_MUXSEL 0u
#define forward_L_0_INPUT_SYNC 2u
#define forward_L_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define forward_L_0_NUM 0u
#define forward_L_0_PORT GPIO_PRT9
#define forward_L_0_SLEWRATE CY_GPIO_SLEW_FAST
#define forward_L_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define forward_L_DRIVEMODE CY_GPIO_DM_PULLUP_DOWN_IN_OFF
#define forward_L_INBUF_ENABLED 0u
#define forward_L_INIT_DRIVESTATE 1u
#define forward_L_INIT_MUXSEL 0u
#define forward_L_INPUT_SYNC 2u
#define forward_L_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define forward_L_NUM 0u
#define forward_L_PORT GPIO_PRT9
#define forward_L_SLEWRATE CY_GPIO_SLEW_FAST
#define forward_L_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* forward_R */
#define forward_R_0_DRIVEMODE CY_GPIO_DM_PULLUP_DOWN_IN_OFF
#define forward_R_0_INBUF_ENABLED 0u
#define forward_R_0_INIT_DRIVESTATE 1u
#define forward_R_0_INIT_MUXSEL 0u
#define forward_R_0_INPUT_SYNC 2u
#define forward_R_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define forward_R_0_NUM 2u
#define forward_R_0_PORT GPIO_PRT9
#define forward_R_0_SLEWRATE CY_GPIO_SLEW_FAST
#define forward_R_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define forward_R_DRIVEMODE CY_GPIO_DM_PULLUP_DOWN_IN_OFF
#define forward_R_INBUF_ENABLED 0u
#define forward_R_INIT_DRIVESTATE 1u
#define forward_R_INIT_MUXSEL 0u
#define forward_R_INPUT_SYNC 2u
#define forward_R_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define forward_R_NUM 2u
#define forward_R_PORT GPIO_PRT9
#define forward_R_SLEWRATE CY_GPIO_SLEW_FAST
#define forward_R_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* pwm_L_pin */
#define pwm_L_pin_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define pwm_L_pin_0_INBUF_ENABLED 0u
#define pwm_L_pin_0_INIT_DRIVESTATE 1u
#define pwm_L_pin_0_INIT_MUXSEL 8u
#define pwm_L_pin_0_INPUT_SYNC 2u
#define pwm_L_pin_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define pwm_L_pin_0_NUM 4u
#define pwm_L_pin_0_PORT GPIO_PRT10
#define pwm_L_pin_0_SLEWRATE CY_GPIO_SLEW_FAST
#define pwm_L_pin_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define pwm_L_pin_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define pwm_L_pin_INBUF_ENABLED 0u
#define pwm_L_pin_INIT_DRIVESTATE 1u
#define pwm_L_pin_INIT_MUXSEL 8u
#define pwm_L_pin_INPUT_SYNC 2u
#define pwm_L_pin_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define pwm_L_pin_NUM 4u
#define pwm_L_pin_PORT GPIO_PRT10
#define pwm_L_pin_SLEWRATE CY_GPIO_SLEW_FAST
#define pwm_L_pin_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* pwm_R_pin */
#define pwm_R_pin_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define pwm_R_pin_0_INBUF_ENABLED 0u
#define pwm_R_pin_0_INIT_DRIVESTATE 1u
#define pwm_R_pin_0_INIT_MUXSEL 8u
#define pwm_R_pin_0_INPUT_SYNC 2u
#define pwm_R_pin_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define pwm_R_pin_0_NUM 6u
#define pwm_R_pin_0_PORT GPIO_PRT10
#define pwm_R_pin_0_SLEWRATE CY_GPIO_SLEW_FAST
#define pwm_R_pin_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define pwm_R_pin_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define pwm_R_pin_INBUF_ENABLED 0u
#define pwm_R_pin_INIT_DRIVESTATE 1u
#define pwm_R_pin_INIT_MUXSEL 8u
#define pwm_R_pin_INPUT_SYNC 2u
#define pwm_R_pin_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define pwm_R_pin_NUM 6u
#define pwm_R_pin_PORT GPIO_PRT10
#define pwm_R_pin_SLEWRATE CY_GPIO_SLEW_FAST
#define pwm_R_pin_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
